name: objective_pay

services:
  postgres:
    image: postgres:14.7
    container_name: objective_pay_postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - objective_pay_pg_data:/var/lib/postgresql/data
      
    healthcheck:

      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: objective_pay-app 
    container_name: objective_pay_app
    
    env_file: .env
    environment:

      POSTGRES_USER: ${POSTGRES_USER}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_HOST: postgres
      
    ports:
      - "4000:4000"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  objective_pay_pg_data: